[package]
name = "axum-example"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.7" }
web-socket = { path = "../../" }
sha-1 = "0.10"
base64 = "0.21"
hyper = "1.2.0"
hyper-util = "0.1"
